# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/push_dialog_base.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_QFieldPushDialogBase(object):
    def setupUi(self, QFieldPushDialogBase):
        QFieldPushDialogBase.setObjectName(_fromUtf8("QFieldPushDialogBase"))
        QFieldPushDialogBase.resize(650, 638)
        self.gridLayout_2 = QtGui.QGridLayout(QFieldPushDialogBase)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.informationStack = QtGui.QStackedWidget()
        self.informationStack.setObjectName(_fromUtf8("informationStack"))
        self.progressPage = QtGui.QWidget()
        self.progressPage.setObjectName(_fromUtf8("progressPage"))
        self.gridLayout_3 = QtGui.QGridLayout(self.progressPage)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.progress_group = QtGui.QGroupBox(self.progressPage)
        self.progress_group.setObjectName(_fromUtf8("progress_group"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.progress_group)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_11 = QtGui.QLabel(self.progress_group)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_6.addWidget(self.label_11)
        self.totalProgressBar = QtGui.QProgressBar(self.progress_group)
        self.totalProgressBar.setProperty("value", 0)
        self.totalProgressBar.setObjectName(_fromUtf8("totalProgressBar"))
        self.verticalLayout_6.addWidget(self.totalProgressBar)
        self.statusLabel = QtGui.QLabel(self.progress_group)
        self.statusLabel.setObjectName(_fromUtf8("statusLabel"))
        self.verticalLayout_6.addWidget(self.statusLabel)
        self.layerProgressBar = QtGui.QProgressBar(self.progress_group)
        self.layerProgressBar.setProperty("value", 0)
        self.layerProgressBar.setObjectName(_fromUtf8("layerProgressBar"))
        self.verticalLayout_6.addWidget(self.layerProgressBar)
        self.gridLayout_3.addWidget(self.progress_group, 0, 0, 1, 1)
        self.informationStack.addWidget(self.progressPage)
        self.selectExtentPage = QtGui.QWidget()
        self.selectExtentPage.setObjectName(_fromUtf8("selectExtentPage"))
        self.gridLayout_4 = QtGui.QGridLayout(self.selectExtentPage)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.groupBox_2 = QtGui.QGroupBox(self.selectExtentPage)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.widget = QtGui.QWidget(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_6 = QtGui.QGridLayout(self.widget)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.yMaxLabel = QtGui.QLineEdit(self.widget)
        self.yMaxLabel.setEnabled(False)
        self.yMaxLabel.setObjectName(_fromUtf8("yMaxLabel"))
        self.gridLayout_6.addWidget(self.yMaxLabel, 3, 2, 1, 1)
        self.yMinLabel = QtGui.QLineEdit(self.widget)
        self.yMinLabel.setEnabled(False)
        self.yMinLabel.setObjectName(_fromUtf8("yMinLabel"))
        self.gridLayout_6.addWidget(self.yMinLabel, 1, 2, 1, 1)
        self.xMinLabel = QtGui.QLineEdit(self.widget)
        self.xMinLabel.setEnabled(False)
        self.xMinLabel.setObjectName(_fromUtf8("xMinLabel"))
        self.gridLayout_6.addWidget(self.xMinLabel, 2, 1, 1, 1)
        self.xMaxLabel = QtGui.QLineEdit(self.widget)
        self.xMaxLabel.setEnabled(False)
        self.xMaxLabel.setObjectName(_fromUtf8("xMaxLabel"))
        self.gridLayout_6.addWidget(self.xMaxLabel, 2, 3, 1, 1)
        self.widget_2 = QtGui.QWidget(self.widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setStyleSheet(_fromUtf8("border: 1px solid #e67e22"))
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.gridLayout_7 = QtGui.QGridLayout(self.widget_2)
        self.gridLayout_7.setMargin(0)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_3 = QtGui.QLabel(self.widget_2)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_7.addWidget(self.label_3, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.widget_2, 2, 2, 1, 1)
        self.gridLayout_5.addWidget(self.widget, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.informationStack.addWidget(self.selectExtentPage)
        self.gridLayout_2.addWidget(self.informationStack, 2, 0, 1, 2)
        QFieldPushDialogBase.setWidget(self.informationStack)
        self.groupBox = QtGui.QGroupBox()
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.manualDir = QtGui.QLineEdit(self.groupBox)
        self.manualDir.setObjectName(_fromUtf8("manualDir"))
        self.gridLayout.addWidget(self.manualDir, 0, 0, 1, 1)
        self.manualDir_btn = QtGui.QPushButton(self.groupBox)
        self.manualDir_btn.setObjectName(_fromUtf8("manualDir_btn"))
        self.gridLayout.addWidget(self.manualDir_btn, 0, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 1, 0, 1, 2)
        QFieldPushDialogBase.setWidget(self.groupBox)
        self.label_2 = QtGui.QLabel()
        self.label_2.setTextFormat(QtCore.Qt.RichText)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        QFieldPushDialogBase.setWidget(self.label_2)
        self.project_lbl = QtGui.QLabel()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.project_lbl.sizePolicy().hasHeightForWidth())
        self.project_lbl.setSizePolicy(sizePolicy)
        self.project_lbl.setObjectName(_fromUtf8("project_lbl"))
        self.gridLayout_2.addWidget(self.project_lbl, 0, 1, 1, 1)
        QFieldPushDialogBase.setWidget(self.project_lbl)
        self.button_box = QtGui.QDialogButtonBox()
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.button_box.setObjectName(_fromUtf8("button_box"))
        self.gridLayout_2.addWidget(self.button_box, 4, 0, 1, 2)
        QFieldPushDialogBase.setWidget(self.button_box)
        self.infoGroupBox = QtGui.QGroupBox()
        self.infoGroupBox.setObjectName(_fromUtf8("infoGroupBox"))
        self.gridLayout_8 = QtGui.QGridLayout(self.infoGroupBox)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.infoLabel = QtGui.QLabel(self.infoGroupBox)
        self.infoLabel.setObjectName(_fromUtf8("infoLabel"))
        self.gridLayout_8.addWidget(self.infoLabel, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.infoGroupBox, 3, 0, 1, 2)
        QFieldPushDialogBase.setWidget(self.infoGroupBox)

        self.retranslateUi(QFieldPushDialogBase)
        self.informationStack.setCurrentIndex(1)

    def retranslateUi(self, QFieldPushDialogBase):
        QFieldPushDialogBase.setWindowTitle(_translate("QFieldPushDialogBase", "Prepare project for QField", None))
        self.progress_group.setTitle(_translate("QFieldPushDialogBase", "Progress", None))
        self.label_11.setText(_translate("QFieldPushDialogBase", "Total", None))
        self.statusLabel.setText(_translate("QFieldPushDialogBase", "Layer", None))
        self.groupBox_2.setTitle(_translate("QFieldPushDialogBase", "Select extent", None))
        self.label_3.setText(_translate("QFieldPushDialogBase", "<html><head/><body><p>The main map canvas<br/>can be panned and<br/>zoomed as usual<br/>while this window is<br/>open.<br/>Try it!</p></body></html>", None))
        self.groupBox.setTitle(_translate("QFieldPushDialogBase", "Export Directory", None))
        self.manualDir_btn.setText(_translate("QFieldPushDialogBase", "...", None))
        self.label_2.setText(_translate("QFieldPushDialogBase", "<html><head/><body><p><span style=\" font-weight:600;\">Project:</span></p></body></html>", None))
        self.project_lbl.setText(_translate("QFieldPushDialogBase", "TextLabel", None))
        self.infoGroupBox.setTitle(_translate("QFieldPushDialogBase", "Information", None))
        self.infoLabel.setText(_translate("QFieldPushDialogBase", "Some layers in this project have not yet been configured. <a href=\"configuration\">Configure project now</a>.", None))

from qgis.gui import QgsDockWidget
